### ISSUE TITLE
module 'dask' has no attribute 'config'

### ISSUE THREAD

**Issue by kumarivin** [Featuretools/predict-next-purchase#7]
`Traceback (most recent call last):
  File "process_data.py", line 1, in <module>
    import featuretools as ft
  File "/Users/trinadhimmedisetty/anaconda3/lib/python3.6/site-packages/featuretools-0.2.1-py3.6.egg/featuretools/__init__.py", line 7, in <module>
    from .synthesis.api import *
  File "/Users/trinadhimmedisetty/anaconda3/lib/python3.6/site-packages/featuretools-0.2.1-py3.6.egg/featuretools/synthesis/__init__.py", line 3, in <module>
    from .api import *
  File "/Users/trinadhimmedisetty/anaconda3/lib/python3.6/site-packages/featuretools-0.2.1-py3.6.egg/featuretools/synthesis/api.py", line 5, in <module>
    from .dfs import dfs
  File "/Users/trinadhimmedisetty/anaconda3/lib/python3.6/site-packages/featuretools-0.2.1-py3.6.egg/featuretools/synthesis/dfs.py", line 5, in <module>
    from featuretools.computational_backends import calculate_feature_matrix
  File "/Users/trinadhimmedisetty/anaconda3/lib/python3.6/site-packages/featuretools-0.2.1-py3.6.egg/featuretools/computational_backends/__init__.py", line 2, in <module>
    from .api import *
  File "/Users/trinadhimmedisetty/anaconda3/lib/python3.6/site-packages/featuretools-0.2.1-py3.6.egg/featuretools/computational_backends/api.py", line 2, in <module>
    from .calculate_feature_matrix import (
  File "/Users/trinadhimmedisetty/anaconda3/lib/python3.6/site-packages/featuretools-0.2.1-py3.6.egg/featuretools/computational_backends/calculate_feature_matrix.py", line 17, in <module>
    from .utils import (
  File "/Users/trinadhimmedisetty/anaconda3/lib/python3.6/site-packages/featuretools-0.2.1-py3.6.egg/featuretools/computational_backends/utils.py", line 9, in <module>
    from distributed import Client, LocalCluster
  File "/Users/trinadhimmedisetty/anaconda3/lib/python3.6/site-packages/distributed/__init__.py", line 3, in <module>
    from . import config
  File "/Users/trinadhimmedisetty/anaconda3/lib/python3.6/site-packages/distributed/config.py", line 13, in <module>
    config = dask.config.config
AttributeError: module 'dask' has no attribute 'config'`

**Comment by kumarivin** [comment]
Issue occurred due to multiple installations of dask.
